### PR TITLE
Add more apple targets

### LINKED ISSUE #40: Add support for all Apple targets
Currently, these targets are missing 
```
iosSimulatorArm64
macosArm64
tvosSimulatorArm64
watchosSimulatorArm64
watchosX64
```

### PR DESCRIPTION
**Pull request by rsinukov**
Fixed #40

### CODE REVIEW

**Review by Him188 — APPROVED** [review]

**Comment by Him188** [comment]
@rsinukov Hi, I figured out that compile-native-platform.gradle is not used anymore. Yamllkt declares platforms here: https://github.com/Him188/yamlkt/blob/769cdc5310a28099ef7fd89e87a082294c8bb502/yamlkt/build.gradle.kts#L36-L45

Maybe I forgot to delete that file in commit https://github.com/Him188/yamlkt/commit/baca1d42d275e4b94ae4c2aa9046f49b278bfb9e... Sorry for that.

**Comment by rsinukov** [comment]
Ok, thanks! 
Do you have any estimates on when a new version will be released?

**Comment by rsinukov** [comment]
Also, any plans on updating kotlin and serialization version?

**Comment by Him188** [comment]
@rsinukov Yes, I will publish a new version with updated Kotlin and serialization in recent 2-3 days.

**Pull request closed without merging**
